### ISSUE TITLE
SUPER ISSUE: Improve screenshot positioning

### ISSUE THREAD

**Issue by Miguelcldn** [bitDubai/fermat-org#213]
Screenshots can't continue being set with constants, we must add in the XML or something so when a developer creates a new WPD sub app, the client (and maybe server) gets those screenshots and show them.

**Comment by Miguelcldn** [comment]
Should this issue be closed?

**Comment by ricardo460** [comment]
Falta renombrar el nombre de unas carpeta en el repositorio de fermat y listo.

**Comment by Miguelcldn** [comment]
Crea el issue y hazlo para cerrar esto :+1:

**Comment by ricardo460** [comment]
cambios Aplicados.

**Comment by Luis-Fernando-Molina** [comment]
@ricardo460 seria bueno que captures los screenshoots de las otras APPs que faltan, porque no se estan mostrando. Gracias



 @Miguelcldn

**Comment by ricardo460** [comment]
@Luis-Fernando-Molina bueno eso es lo que falta, actualizar y añadir los screenshots de las APPS. Pero actualmente se estan presentado problemas al abrir la APK de fermat y estoy esperando que @arnaldos me avise que tiene los screenshots, para actualizar los viejos y añadir los nuevos.

**Comment by Luis-Fernando-Molina** [comment]
hace falta Arnaldo para eso?

**Comment by ricardo460** [comment]
Bueno en realidad no, pero el tiene la aplicación en el teléfono y en su computadora. Además tiene la facilidad de trabajar de cerca con fermat y conocer sus avances.

Matías me puso en contacto con el, cuando estaba discutiendo sobre los screenshots y fue por eso que lo busque a el. Pero tendré que buscar otras opciones para agilizar el proceso.

**Comment by arnaldos** [comment]
@ricardo460 te comparto los screenshoot que tengo disponibles, hay algunas vistas aun definiéndose apenas tenga algo de eso te envio las vistas que se vallan actualizando.

![screenshot_2015-11-27-17-19-07](https://cloud.githubusercontent.com/assets/13594347/12314906/7fefd496-ba47-11e5-9135-c97648919b72.png)
![screenshot_2015-12-15-00-33-09](https://cloud.githubusercontent.com/assets/13594347/12314907/7ff56ef6-ba47-11e5-852d-e82dbca8bfc5.png)
![screenshot_2015-12-15-00-34-06](https://cloud.githubusercontent.com/assets/13594347/12314908/7ff911a0-ba47-11e5-8255-789bc48bc0a1.png)
![screenshot_2015-12-15-00-34-34](https://cloud.githubusercontent.com/assets/13594347/12314909/7ffdddde-ba47-11e5-93f4-c1899cb46bc5.png)
![screenshot_2015-12-15-00-34-49](https://cloud.githubusercontent.com/assets/13594347/12314914/8ddc071e-ba47-11e5-86c1-7f3d50af78af.png)
![screenshot_2015-12-15-00-35-49](https://cloud.githubusercontent.com/assets/13594347/12314915/8de039a6-ba47-11e5-90b1-a8a8d705c73d.png)
![screenshot_2015-12-15-14-17-32](https://cloud.githubusercontent.com/assets/13594347/12314916/8de47444-ba47-11e5-8d80-60aab00158c7.png)
![screenshot_2015-12-30-10-41-10](https://cloud.githubusercontent.com/assets/13594347/12314917/8deb0656-ba47-11e5-98b6-590aa43497a6.png)
![screenshot_2015-12-30-10-41-44](https://cloud.githubusercontent.com/assets/13594347/12314918/8def9946-ba47-11e5-9209-58ee9472fc9d.png)
![screenshot_2015-12-30-10-42-24](https://cloud.githubusercontent.com/assets/13594347/12314919/8df5cfb4-ba47-11e5-99d2-a1313f87b741.png)
![screenshot_2015-12-30-10-42-31](https://cloud.githubusercontent.com/assets/13594347/12314920/8dfaf9e4-ba47-11e5-8137-0a4fa1271c05.png)
![screenshot_2015-12-30-10-43-20](https://cloud.githubusercontent.com/assets/13594347/12314921/8dfca9f6-ba47-11e5-96ea-db258b29a7e3.png)
![screenshot_2015-12-31-01-46-05](https://cloud.githubusercontent.com/assets/13594347/12314923/8e07679c-ba47-11e5-9222-d0ee93a984fa.png)
![screenshot_2015-12-31-01-46-15](https://cloud.githubusercontent.com/assets/13594347/12314922/8e06959c-ba47-11e5-8645-6ddd40d4caf3.png)
![screenshot_2015-12-31-01-46-21](https://cloud.githubusercontent.com/assets/13594347/12314924/8e0e4152-ba47-11e5-9402-38d3d1a0c018.png)
![screenshot_2015-12-31-01-46-46](https://cloud.githubusercontent.com/assets/13594347/12314925/8e10e36c-ba47-11e5-8cc4-44403159534f.png)
![screenshot_2016-01-06-15-49-33](https://cloud.githubusercontent.com/assets/13594347/12314940/b6a422b2-ba47-11e5-947d-75b7cf7b3fdf.png)
![screenshot_2016-01-06-15-50-10](https://cloud.githubusercontent.com/assets/13594347/12314941/b6a7d4a2-ba47-11e5-9cb3-edef73a374a1.png)
![screenshot_2016-01-06-15-50-39](https://cloud.githubusercontent.com/assets/13594347/12314942/b6ad28b2-ba47-11e5-9bca-e3c00e7ed2f8.png)
![screenshot_2016-01-06-15-51-01](https://cloud.githubusercontent.com/assets/13594347/12314943/b6b16738-ba47-11e5-985e-ffe0eacecce3.png)
![screenshot_2016-01-13-21-20-53](https://cloud.githubusercontent.com/assets/13594347/12314944/b6b7bc0a-ba47-11e5-9475-76c948bea383.png)
![screenshot_2016-01-13-21-21-04](https://cloud.githubusercontent.com/assets/13594347/12314945/b6c08b78-ba47-11e5-81b7-59736ffc371d.png)
![screenshot_2016-01-13-21-21-14](https://cloud.githubusercontent.com/assets/13594347/12314946/b6c746f2-ba47-11e5-8e3e-4a3360289adb.png)
![screenshot_2016-01-13-21-21-21](https://cloud.githubusercontent.com/assets/13594347/12314947/b6ccfbec-ba47-11e5-9701-ca2cf61f7263.png)
![screenshot_2016-01-13-21-23-24](https://cloud.githubusercontent.com/assets/13594347/12314948/b6d15390-ba47-11e5-9104-1745e5bc6f69.png)
![screenshot_2016-01-13-21-24-34](https://cloud.githubusercontent.com/assets/13594347/12314949/b6d7e91c-ba47-11e5-845e-a1dbfc733f56.png)
![screenshot_2016-01-13-21-25-04](https://cloud.githubusercontent.com/assets/13594347/12314951/b6e5ef6c-ba47-11e5-9407-4711a0fa9592.png)
![screenshot_2016-01-13-21-25-13](https://cloud.githubusercontent.com/assets/13594347/12314950/b6e32304-ba47-11e5-8812-4a8bcb94555c.png)
![screenshot_2016-01-13-21-25-25](https://cloud.githubusercontent.com/assets/13594347/12314952/b6e85914-ba47-11e5-9ed7-1514ea6dbe0a.png)
![screenshot_2016-01-13-21-26-31](https://cloud.githubusercontent.com/assets/13594347/12314953/b6ef55e8-ba47-11e5-99f5-47fe9cc3a29d.png)
![screenshot_2016-01-13-21-26-40](https://cloud.githubusercontent.com/assets/13594347/12314954/b6f54714-ba47-11e5-8cc5-89c008c9d7d9.png)
