### ISSUE TITLE
Get component's attribute screenshots

### ISSUE THREAD

**Issue by Miguelcldn** [bitDubai/fermat-org#326]
Todos los componentes podrían o no tener un atributo "screenshots" que puede ser "true" o "false". O si XML lo permite podría estar solo la palabra "screenshots" y de estarlo se considera true (así como el atributo `readonly` en HTML). Sea como sea se haga, se agradece comentar aquí cómo se debe hacer en el manifest.

**Comment by ricardo460** [comment]
Ya no es necesario la lectura del atributo screenshots, ya que se encontró una nueva y mejor manera de realizar la lectura de los screenshots de cada componente.
