### ISSUE TITLE
Test process in COR is not being seen

### ISSUE THREAD

**Issue by Miguelcldn** [bitDubai/fermat-org#335]
In the fermatManifest.xml on master, the last process (the test process located in COR platform) is sent by the API with steps = []

Sent request:

URL : http://52.35.117.6:3000/v1/repo/procs/

Response (Extract):

```JavaScript
[51]:
_id: "568c199670277a0569ee54fb"
desc: "This is a process intended to test the workflow drawing"
name: "test process"
next: null
platfrm: "COR"
prev: null
steps: []
upd_at: "568c199670277a0569ee54fa"
```

When fixed inform @acostarodrigo

**Comment by fuelusumar** [comment]
@acostarodrigo esto es porque el step no tiene layer, platform o super_layer asignado, estos datos son necesarios para vincular un paso del workflow con algún componente. O mejor dicho, todo paso, decision o micro proceso toma lugar dentro de un componente, y debe ser especificado dentro del step para que sea valido

**Comment by acostarodrigo** [comment]
hola, @Miguelcldn @fuelusumar yo solo quiero ver en un flujo de ejemplo las opciones para hacer bucles, decisiones, etc.

@Miguelcldn me avisas cuando eso ya esté listo asi creo los de DAP incluyendo esos flujos. Por favor, esto hace como 2 semanas que se pidió.
