### ISSUE TITLE
create route for insert, update and delete layer

### ISSUE THREAD

**Issue by fuelusumar** [bitDubai/fermat-org#348]
- [x] INSERT
- [x] UPDATE
- [x] DELETE
* Esta ruta debe recibir por post todos los datos necesarios para crear una layer
* Como las layers están ordenadas, al insertar una, esta debe tener orden y desplazar a las demás layers que tengan un orden mayor o igual
* Como respuesta esta ruta debe dar la layer ya insertada (con id y todos sus datos)
* Cuando se elimina un layer hay que eliminar todos los componentes que le pertenecen (esto solo para solo un role superior) y restablecer el orden

**Recuerden usar seguridad y versionamiento**
**Las referencias necesarias son por medio de id's pasados por parametros**
#256 link

**Comment by kyxer** [comment]
Confirmar funcionamiento de este endpoint @fuelusumar Tenemos dos caso
Insertar layer dada una posición (Se mueven las demás layers hacia delante)
Insertar layer de ultimo no pasa nada.

**Comment by fuelusumar** [comment]
Si, asi mismo es @kyxer. Es igual para platform y superlayer que son las otras estructuras que tienen orden, cuando se elmina hay que cambiarle tambien el orden todas las que tienen un orden mayor, el mismo caso aplica para platform y superlayer.
