### ISSUE TITLE
create route for insert, update and delete component

### ISSUE THREAD

**Issue by fuelusumar** [bitDubai/fermat-org#349]
- [x] INSERT
- [x] UPDATE
- [x] DELETE
* Esta ruta debe recibir por post todos los datos necesarios para crear un componente
* Como respuesta esta ruta debe dar el componente ya insertado (con id y todos sus datos)
* Cuando se elimina un componente hay que eliminar todos los comp_dev y status que le pertenecen

**Recuerden usar seguridad y versionamiento**
**Las referencias necesarias son por medio de id's pasados por parametros**
#256 link

**Comment by kyxer** [comment]
@fuelusumar tambien agregue la ruta /comps/:comp_id para poder obtener la informacion a listar
ahora mi duda es la siguiente este es el response
```javascript
   {
	"_platfrm_id": null,
	"_suprlay_id": "56947576e65751291d269e60",
	"_layer_id": "56947577e65751291d269e90",
	"name": "device hardware",
	"type": "addon",
	"description": "",
	"difficulty": 0,
	"code_level": "concept",
	"repo_dir": "OSA/addon/android/fermat-osa-addon-android-device-hardware-bitdubai",
	"scrnshts": false,
	"found": false,
	"devs": ["56947577e65751291d269f22", "56947577e65751291d269f26"],
	"certs": [],
	"life_cycle": ["56947577e65751291d269f29", "56947577e65751291d269f2c", "56947577e65751291d269f2f", "56947577e65751291d269f32"],
	"upd_at": "56947577e65751291d269f35",
	"_id": "56947577e65751291d269f1e"
}
```
Se necesita llenar algun campo extra?

**Comment by kyxer** [comment]
Create test for comps routes
