### ISSUE TITLE
Create script to copy the repository folder fermat.

### ISSUE THREAD

**Issue by ricardo460** [bitDubai/fermat-org#356]
Se necesita crear un script para copiar la carpeta [wallet_screenshots](https://github.com/bitDubai/fermat/tree/master/seed-resources)
del repositoria de fermat a [images](https://github.com/bitDubai/fermat-org/tree/master/platform-visualization/images), donde sera utilizada por un script ya creado.

La actualización de esta carpeta puede ser de mes en mes.

Necesario para #213.

**Comment by Miguelcldn** [comment]
Por qué no sacar las imagenes de wallet_screenshots directamente? Si es por el preloading, puede simplemente no pre-cargarse (puesto que no es lo primero que ve el usuario)

**Comment by ricardo460** [comment]
Se requiere de esta forma, ya que se necesita armar una estructura similar a esta: 
```javascript
{
    group:{
        layer:{
            wallet:{
                name:"",
                screenshots:{
                    screenshot_1:"",
                    screenshot_2:"",
                    .
                    .
                    .
                }
            }
        }
    }
}
``` 
Esta estructura es necesaria para obtener la ubicación exacta de cada screenshot y saber a que componente pertenece. Esto no es imposible de la forma que comentas, en realidad ya la habia puesto aprueba con : 
```javascript
	function addImage(name, _src, num){
		var src = _src + num + ".png";
        $.ajax({
            url: src,
            async :  false,
        }).success(function() {
			SCREENSHOTS[name]["screenshots"]["Screenshots_" + num] = src;
     		addImage(name, _src, num + 1);
        });
	}
```
Se requeria que la llamada fuera synchronous ya que la respuesta tardaba en ser respondida, esta función va comprobando los url, que me permite saber la cantidad de screenshot que posee cada carpeta y su dirección absoluta para luego ser utilizadas en fermat-org.

Realizar este tipo de llamadas cada ves que se cargue fermat-org las considero innecesarias ya que saber la cantidad de screenshot que posee una wallet 'NO ES DE VIDA O MUERTE' para fermat-org, lo que se me ocurrió para optimizar al máximo este proceso fue la creación de un script que construya un json con la estructura requerida para mostrar los screenshot y saber su posición en la tabla (#345), pero para esto se requiere que esa carpeta se encuentre en el repositorio de fermat-org y así optimar todo el proceso.

También se requiere que se actualice la carpeta en vez en mes ya que no todos los días cambian o añaden nuevas pantallas a la apk de fermat.

@Miguelcldn
