### ISSUE TITLE
Restructure of components table

### ISSUE THREAD

**Issue by Miguelcldn** [bitDubai/fermat-org#357]
As we are preparing for Fermat V3, the user will have the ability of move a component from one layer to another, so, the table structure as we have been working with, will no longer be useful for this task. Now we need the table to have a more structured behavior, where the table will be composed by platforms and super layers, and those will be at the same time composed by layers, where each layer will contain their components. This issue include that everything works as expected.

necessary #377.

**Comment by emmanuelcolina** [comment]
- [x] Organizar todos los objetos tal que se tenga un comportamiento mas estructurado
-[ ] Integracion de la nueva estructura al proyecto
