### ISSUE TITLE
Create resource lock

### ISSUE THREAD

**Issue by fuelusumar** [bitDubai/fermat-org#361]
- [x] Crete structures
- [x] Crete services
- [x] Crete module
- [x] Do logic

#256 link

![Lock Logic](https://cloud.githubusercontent.com/assets/6330976/12208124/7d43f604-b629-11e5-881c-d8822a4122b0.jpg)

@Miguelcldn and @Luis-Fernando-Molina check this out!

**Comment by Miguelcldn** [comment]
Good! I was expecting a markdown readme as a more permanent documentation but this is enough to understand the logic we are going to follow
