### ISSUE TITLE
Create function to hide buttons

### ISSUE THREAD

**Issue by ricardo460** [bitDubai/fermat-org#370]
Se necesita crear una función para ocultar los botones que se muestran, para organizar y evitar repetir código innecesariamente.

**Comment by Miguelcldn** [comment]
```
/**
     * Hides an element vanishing it and then eliminating it from the DOM
     * @param {DOMElement} element         The element to eliminate
     * @param {Number}     [duration=1000] Duration of the fade animation
     * @param {Boolean}    [keep=false]     If set true, don't remove the element, just dissapear
     */
helper.hide = function(element, duration, keep)
```

Es la función que hace eso, no?

**Comment by ricardo460** [comment]
No. yo dijo crear una nueva para realizar esta operación:
```
            if( $('#developerButton') != null ) helper.hide($('#developerButton'), 1000);
            if( $('#showFlows') != null ) helper.hide($('#showFlows'), 1000);
```

Ya que se están usando de forma individual al presionar un botón ejemplo en:

```
button.addEventListener('click', function() {
                    showDeveloper(id);
                    helper.hide(button, 1000, false);
                    helper.hide('showFlows', 1000, false);
                });
```
y así también con el botón Show flow al presionar.se debe desaparecer el boton showDeveloper de forma manual.

Esto lo que genera es repetición de codigo a medida que una va añadiendo botones, cada ves se va ir añadiendo mas codigo por cada evento click.
