### ISSUE TITLE
Draw and position the tiles created and edited.

### ISSUE THREAD

**Issue by ricardo460** [bitDubai/fermat-org#395]
Después de haber seleccionado todas las opciones para la creación o edición de un componente, se debe mostrar dicho componente con todas las configuraciones seleccionadas y en su posición final. También se necesita añadir, editar o eliminar dicho componente de la variable table, para su posterior dibujado.

Tareas a realizar:

- [x] creación de nuevo componente:
   - [x] Crear un nuevo plano para el nuevo componente(Aplica solamente para la creación de un nuevo componente). 
   - [x] Posicionar plano.
   - [x] Dibujar plano con su respectiva configuración.

- [x] Edición de un Componente
   - [x] Llenar campos con su configuración actual.
   - [x] Editar plano con su nueva configuración.
   - [x] Posicionar plano en su posición final.

- [x] Eliminación de un Componente.
   - [x] Borrar plano(Objeto) y modificar la variable table.

- [x] Configurar animación de los nuevos componentes.

Necesario para #377.

**Comment by ricardo460** [comment]
First Version Launched(creating a new component) @Miguelcldn. 
![captura de pantalla 82](https://cloud.githubusercontent.com/assets/13169767/12601383/d665541a-c472-11e5-90af-bedc7b238a57.png)

**Comment by Miguelcldn** [comment]
Me parece bien para empezar :+1:
