### ISSUE TITLE
Register users

### ISSUE THREAD

**Issue by campol** [bitDubai/fermat-org#398]
@fuelusumar 
Recibir codigo de autorizacion de aplicacion registrada en github
Pedir a github el acces token pasando el codigo de autorizacion
Con el access token consultar datos del usuario que hizo login
Guardar los datos del usuario en base de datos en la tabla Users y developer

**Comment by Miguelcldn** [comment]
Llena los campos de Labels, Milestone y Assignee si aplican por favor, para tener un contexto de este issue
