### ISSUE TITLE
Improve the design of fields with css

### ISSUE THREAD

**Issue by ricardo460** [bitDubai/fermat-org#419]
Se necesita Mejorar el diseño de los campos de fermat-edit con css y reparar bug de visualización para las diferentes pantallas. Acomodando la dimensiones de los campos.

Necesario para #377.

**Comment by ricardo460** [comment]
![captura de pantalla 88](https://cloud.githubusercontent.com/assets/13169767/12772534/255f9260-ca04-11e5-980a-c99007e9845c.png)
Versión original.

**Comment by ricardo460** [comment]
![sin titulo](https://cloud.githubusercontent.com/assets/13169767/12825562/1f0a4126-cb49-11e5-8b26-fb3e953f0990.png)
Version normal,
![img_04022016_025843](https://cloud.githubusercontent.com/assets/13169767/12825623/78177694-cb49-11e5-8a11-8a546234513a.png)
Bordes redondeados.
@Miguelcldn

**Comment by Miguelcldn** [comment]
Me gusta mas cuadrado, y los triángulos están muy grandes

**Comment by DarilRodriguez** [comment]
@Miguelcldn 
1:
![img_05022016_012355](https://cloud.githubusercontent.com/assets/7703770/12838158/1158b6c4-cba9-11e5-9cd6-c84f3c6250a2.png)
2:
![img_05022016_013533](https://cloud.githubusercontent.com/assets/7703770/12838163/218b7af4-cba9-11e5-8e56-4f86af2f2f7f.png)

**Comment by Miguelcldn** [comment]
Me gusta la versión 2, que va mejor con las flechas de la vista principal :+1:
